# Basic site configuration
title: 'mialikestech.dev'
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
root: /
url: "https://mialikestech.dev" # the base hostname & protocol for your site, e.g. http://example.com
listen_for_clients_preferred_style: true # Context-switched dark mode. Why the variable name is so long I do not know.

markdown: kramdown

# Pages to be included in the site nav header (`~/ $ ls` and the directory listing)
header_pages:
  - index.md
  - posts.md
  - about.md

# Global site footer
footer: 'For privacy and license information, please consult <a href="/tos/">our TOS</a>'

# Jekyll settings
theme: jekyll-theme-console
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll_picture_tag

# Create blog category listings with jekyll-archives
jekyll-archives:
  enabled: [category, categories]
  layouts:
    category: category
  permalinks:
    category: /posts/:name/

# Responsive images with jekyll_picture_tag
picture:
  source: "assets/images"
  output: "assets/images/responsive"
  fast_build: development
  ignore_missing_images: development

# Jekyll compose frontmatter definitions
jekyll_compose:
  default_front_matter:
    drafts:
      rich-title: "Give Full Name Here"
      category:
    posts:
      rich-title: "Give Full Name Here"
      category:

# Files excluded from static generation
exclude:
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .vscode/
  - .github/
